apiVersion: v1
kind: Service
metadata:
  name: leader-election-app
spec:
  selector:
    app: leader-election-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

