apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: leader-election-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leader-election-app
  template:
    metadata:
      labels:
        app: leader-election-app
    spec:
      serviceAccountName: leader-election-app
      containers:
      - name: leader-election-app
        image: leader-election-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

